### PR TITLE
15.10.2 WIP

### PR DESCRIPTION
**Pull request by tophf**
@eight04, could you finish this? I couldn't fix `_external_module is not defined` error. And the build grew significantly (+150kB) but that's unavoidable due to the use of `css-tree` in three rules that seem useful.

### CODE REVIEW

**Comment by eight04** [comment]
I'll take a look

**Comment by eight04** [comment]
https://unpkg.com/browse/css-tree@2.3.1/lib/data.js

css-tree uses `require` in esm to load JSON data. After rollup, the "module" module, is referenced as `_external_module`:
https://github.com/openstyles/stylelint-bundle/blob/fe9522f0c2189714ee5af7b7f39eaeea98323e5d/rollup.config.js#L92
When css-tree tries to call `_external_module.createRequire()`, an error is thrown.

I think there are two ways to fix it:

### Make rollup-plugin-cjs-es support `createRequire`

The plugin has to strip the `import { createRequire } ...` statement and transform `require()` function call inside esm. It should also respect the argument of `createRequire` if possible (usually is `import.meta.url`.)

I don't know how css-tree bundled successfully. [They use esbuild](https://github.com/csstree/csstree/blob/master/scripts/bundle.js) and it seems that [esbuild doesn't support `createRequire` statements either](https://github.com/evanw/esbuild/issues/1828).

### It seems that there is a pre-built bundle in css-tree

Maybe we can redirect `css-tree` to `css-tree/dist/csstree.esm.js`.

https://github.com/eight04/rollup-plugin-cjs-es/blob/2e034406f420b67b9988ca048f5ffb9fa2daa968/index.js#L164-L167

**Comment by tophf** [comment]
Adding `{ find: "css-tree", replacement: require.resolve("css-tree/dist/csstree.esm") },` fixes the problem at the cost of extra ~70kB. I think it's fine, but if you can find another solution that shrinks the build it'd be great.

**Comment by eight04** [comment]
If we still want to bundle them without fixing cjs-es, we can write some `re` rules to replace those `xxx = require("xxx.json")` with the actual JSON content. Similar to
https://github.com/openstyles/stylelint-bundle/blob/fe9522f0c2189714ee5af7b7f39eaeea98323e5d/rollup.config.js#L44-L46

Also have to strip the `createRequire` call so it doesn't throw
```js
{
  match: ...
  test: /const require = createRequire.*/g,
  replace: ""
}
```

**Comment by tophf** [comment]
I see this data is already inside `dist/csstree.esm.js`, which is probably why it adds 70kB, so I guess there's no way to reduce it back to where it was even if we compile css-tree ourselves.

**Pull request merged**
