### PR TITLE
Stylelint 13.8.0

### PR DESCRIPTION
**Pull request by tophf**
This PR uses the most recent v8.0.0 branch and includes its commits.

* moved the bundles into `dist`
* converted command-line scripts into JS
* merged `build` and `buildscript` as it doesn't make sense to use them separately
* rewrote tests to use both output bundles when running in node
* `uglify-es` 3.3.7 is used because new versions are all bugged
* removed `updates` script after seeing the bugs in uglify-es - it's more reliable to update stuff manually

@eight04, I couldn't make `babelify` transform work with `browserify` so maybe you could look into it?
@Mottie, please give us all write access and optionally review the PR.

Also, someone should probably publish it in npm so it can be used by Stylus?

### CODE REVIEW

**Comment by Mottie** [comment]
> Also, someone should probably publish it in npm so it can be used by Stylus?

We could create a GitHub action to auto-publish, see https://github.com/fregante/ghatemplates#npm-publish

He helped me set it up for this repo: https://github.com/Mottie/github-reserved-names/blob/master/.github/workflows/npm-publish.yml

**Review by Mottie — APPROVED** [review]
I didn't actually run the code, but the changes LGTM.

**Comment by tophf** [comment]
@Mottie, @eight04, I don't have access to NPM so could you set up an action like the [above one](https://github.com/Mottie/github-reserved-names/blob/master/.github/workflows/npm-publish.yml)? AFAICT, it requires knowing the npm password/token and setting it up in the repo's settings for "secrets". Or just merge this and push it to npm if the action is too much hassle.

**Comment by Mottie** [comment]
I added the npm publish workflow... it looks like it worked, 13.8.0 is on npm now. 

It took me a few tries until I released the package was published under the openstyles npm account and not my personal account 🤣 - I had to make a "automation" token from here: https://www.npmjs.com/settings/openstyles/tokens

**Pull request merged**
